package com.leetcode.oj.problem.solution.easy;

/**
 * URL: <a href="https://leetcode.com/problems/find-the-difference/description/">Find the Difference</a>
 * <p>
 * Given two strings s and t which consist of only lowercase letters.
 * <p>
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * <p>
 * Find the letter that was added in t.
 * <p>
 * Example:
 * <p>
 * Input:
 * s = "abcd"
 * t = "abcde"
 * <p>
 * Output:
 * e
 * <p>
 * Explanation:
 * 'e' is the letter that was added.
 * <p>
 * Created by leeyee on 2017/8/12.
 */
public class FindTheDifference {

    public char findTheDifference(String s, String t) {

        if (s.length() == 0 && t.length() == 1) return t.charAt(0);

        char diffChar = '\u0000';

        for (char sChar : s.toCharArray()) {

            int idx = t.indexOf(sChar);

            if(idx > -1){
                char [] tChars = t.toCharArray();
                tChars[idx] = '\u0000';
                t = new String(tChars);
            }

        }

        for (char c : t.toCharArray()) {
            if(c!= '\u0000'){
                diffChar = c;
                break;
            }
        }

        return diffChar;

    }

    // TODO: optimization
}
